### ISSUE TITLE
Metrics optimization

### ISSUE THREAD

**Issue by samuelecalamita** [diva-e-aem/xwalk-boilerplate#14]
We need to optimize the page speed score:
https://pagespeed.web.dev/analysis/https-main--xwalk-boilerplate--diva-e-aem-aem-live/cga6dwuqal?form_factor=mobile

**Comment by samuelecalamita** [comment]
- [ ] add aem.js from [here](https://github.com/adobe-rnd/aem-boilerplate-xwalk/blob/main/scripts/aem.js) to our project 
- [ ] rewrite the tasks in the task folder so that are named like the aem.js exported functions
- [ ] in the hlx object call the new exported tasks in the right order

**Comment by ifahrentholz** [comment]
Adobe boilerplate:
https://main--aem-boilerplate-xwalk--adobe-rnd.aem.live

diva-e boilerplate:
https-main--xwalk-boilerplate--diva-e-aem-aem-live

diva-e boilerplate (doc based): 
https://33-maints-refactor--eds-editorial--ifahrentholz.hlx.live
